In [1]:
import pandas as pd
import numpy as np
import sys
import os
import time
import random
import copy
import math
import scanpy as sc
%matplotlib inline
from matplotlib import pyplot as plt
import matplotlib as mpl

import seaborn as sns
import autoreload
params = {
    'font.size': 12,
    'axes.titlesize': 12,
    'axes.labelsize': 12,
    'legend.fontsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'font.family': "Helvetica",
    'pdf.fonttype': 42,
    'ps.fonttype': 42,
    'figure.dpi': 300
   }

mpl.rcParams.update(params)

sns.set_style("ticks")

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

out_dir = "processed_data/stats_tests"
#import auto reload
%load_ext autoreload
%autoreload 2

CountsFile = '../data/Combined_PC_Labeled.h5ad'

/home/mswift/local/anaconda3/envs/singlecell/lib/python3.6/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex

In [2]:
adata = sc.read_h5ad(CountsFile)

In [6]:
changeoDbH = pd.read_csv('/home/mswift/B_cells/SharedData/ShazamQCedIGH.tab', sep = '\t', index_col=0)

In [34]:
changeoDbH = changeoDbH.drop_duplicates(subset=['cell', 'CLONE'])

In [44]:
merged = pd.merge(adata.obs, changeoDbH.set_index('cell'), left_index=True, right_index=True, how='left')

In [45]:
merged

,batch,Donor,parsing,Exp_Labels,Condition_Labels,SEQUENCE_ID,SEQUENCE_INPUT,FUNCTIONAL,IN_FRAME,STOP,MUTATED_INVARIANT,INDELS,LOCUS,V_CALL,D_CALL,J_CALL,SEQUENCE_VDJ,SEQUENCE_IMGT,V_SEQ_START,V_SEQ_LENGTH,V_GERM_START_VDJ,V_GERM_LENGTH_VDJ,V_GERM_START_IMGT,V_GERM_LENGTH_IMGT,NP1_LENGTH,D_SEQ_START,D_SEQ_LENGTH,D_GERM_START,D_GERM_LENGTH,NP2_LENGTH,J_SEQ_START,J_SEQ_LENGTH,J_GERM_START,J_GERM_LENGTH,JUNCTION,JUNCTION_LENGTH,GERMLINE_IMGT,V_SCORE,V_IDENTITY,V_EVALUE,V_CIGAR,D_SCORE,D_IDENTITY,D_EVALUE,D_CIGAR,J_SCORE,J_IDENTITY,J_EVALUE,J_CIGAR,FWR1_IMGT,FWR2_IMGT,FWR3_IMGT,FWR4_IMGT,CDR1_IMGT,CDR2_IMGT,CDR3_IMGT,CLONE,GERMLINE_IMGT_D_MASK,GERMLINE_V_CALL,GERMLINE_D_CALL,GERMLINE_J_CALL,MU_COUNT_SEQ_R,MU_COUNT_SEQ_S,MU_FREQ_SEQ_R,MU_FREQ_SEQ_S,ISOTYPE_by_splice,ISOTYPE
PASL_2_PA_11_plate_1_D11,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PASL_2_PA_11_plate_1_B8,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PASL_2_PA_11_plate_1_C2,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PASL_2_PA_11_plate_1_G10,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PASL_2_PA_11_plate_1_F1,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B107906_C14,8,SS2,B107906,PlasmaCells_2,PlasmaCells,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B107914_M3,8,SS2,B107914,PlasmaCells_1,PlasmaCells,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B107906_P14,8,SS2,B107906,PlasmaCells_2,PlasmaCells,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B107906_C22,8,SS2,B107906,PlasmaCells_2,PlasmaCells,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B107914_A20,8,SS2,B107914,PlasmaCells_1,PlasmaCells,bracer_B107914_A20_TRINITY_DN1_c11_g1_i1_H SS2_TS,GGTATCAACGCAGAGTACATGGGAGCTCTGAGAGAGGAGCCCAGCC...,True,True,False,NaN,False,IGH,"IGHV3-23*01,IGHV3-23D*01","IGHD2-21*01,IGHD2-21*02",IGHJ4*02,GAGGTGCAGCTGTTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGG...,GAGGTGCAGCTGTTGGAGTCTGGGGGA...GGCTTGGTACAGCCTG...,160.0,296.0,1.0,296.0,1.0,320.0,6.0,462.0,10.0,6.0,10.0,2.0,474.0,44.0,5.0,44.0,TGTGCGAAAGAGTTCGGATTGTGGTGGGTCTTTGACTACTGG,42.0,GAGGTGCAGCTGTTGGAGTCTGGGGGA...GGCTTGGTACAGCCTG...,463.0,1.0,5.260000e-132,159S296=,19.9,1.0,0.51,461S5N10=,85.3,1.0,1.960000e-20,473S4N44=,GAGGTGCAGCTGTTGGAGTCTGGGGGA...GGCTTGGTACAGCCTG...,ATGAGCTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTCT...,TACTACGCAGACTCCGTGAAG...GGCCGGTTCACCATCTCCAGAG...,TGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAG,GGATTCACCTTT............AGCAGCTATGCC,ATTAGTGGTAGT......GGTGGTAGCACA,GCGAAAGAGTTCGGATTGTGGTGGGTCTTTGACTAC,1047.0,GAGGTGCAGCTGTTGGAGTCTGGGGGA...GGCTTGGTACAGCCTG...,IGHV3-23*01,IGHD2-21*01,IGHJ4*02,0.0,0.0,0.0,0.0,IGHA1,IGHA1

In [46]:
adata.obs = merged

In [48]:
adata

AnnData object with n_obs × n_vars = 5851 × 60633
    obs: 'batch', 'Donor', 'parsing', 'Exp_Labels', 'Condition_Labels', 'SEQUENCE_ID', 'SEQUENCE_INPUT', 'FUNCTIONAL', 'IN_FRAME', 'STOP', 'MUTATED_INVARIANT', 'INDELS', 'LOCUS', 'V_CALL', 'D_CALL', 'J_CALL', 'SEQUENCE_VDJ', 'SEQUENCE_IMGT', 'V_SEQ_START', 'V_SEQ_LENGTH', 'V_GERM_START_VDJ', 'V_GERM_LENGTH_VDJ', 'V_GERM_START_IMGT', 'V_GERM_LENGTH_IMGT', 'NP1_LENGTH', 'D_SEQ_START', 'D_SEQ_LENGTH', 'D_GERM_START', 'D_GERM_LENGTH', 'NP2_LENGTH', 'J_SEQ_START', 'J_SEQ_LENGTH', 'J_GERM_START', 'J_GERM_LENGTH', 'JUNCTION', 'JUNCTION_LENGTH', 'GERMLINE_IMGT', 'V_SCORE', 'V_IDENTITY', 'V_EVALUE', 'V_CIGAR', 'D_SCORE', 'D_IDENTITY', 'D_EVALUE', 'D_CIGAR', 'J_SCORE', 'J_IDENTITY', 'J_EVALUE', 'J_CIGAR', 'FWR1_IMGT', 'FWR2_IMGT', 'FWR3_IMGT', 'FWR4_IMGT', 'CDR1_IMGT', 'CDR2_IMGT', 'CDR3_IMGT', 'CLONE', 'GERMLINE_IMGT_D_MASK', 'GERMLINE_V_CALL', 'GERMLINE_D_CALL', 'GERMLINE_J_CALL', 'MU_COUNT_SEQ_R', 'MU_COUNT_SEQ_S', 'MU_FREQ_SEQ_R', 'MU_FREQ_SEQ_S', 'ISOTYPE_by_splice', 'ISOTYPE'

In [51]:
adata.obs['CLONE'].value_counts()

2175.0    38
1913.0    15
1965.0     6
1502.0     6
1462.0     6
          ..
1491.0     1
1737.0     1
2201.0     1
162.0      1
1200.0     1
Name: CLONE, Length: 1170, dtype: int64

In [47]:
adata.obs

,batch,Donor,parsing,Exp_Labels,Condition_Labels,SEQUENCE_ID,SEQUENCE_INPUT,FUNCTIONAL,IN_FRAME,STOP,MUTATED_INVARIANT,INDELS,LOCUS,V_CALL,D_CALL,J_CALL,SEQUENCE_VDJ,SEQUENCE_IMGT,V_SEQ_START,V_SEQ_LENGTH,V_GERM_START_VDJ,V_GERM_LENGTH_VDJ,V_GERM_START_IMGT,V_GERM_LENGTH_IMGT,NP1_LENGTH,D_SEQ_START,D_SEQ_LENGTH,D_GERM_START,D_GERM_LENGTH,NP2_LENGTH,J_SEQ_START,J_SEQ_LENGTH,J_GERM_START,J_GERM_LENGTH,JUNCTION,JUNCTION_LENGTH,GERMLINE_IMGT,V_SCORE,V_IDENTITY,V_EVALUE,V_CIGAR,D_SCORE,D_IDENTITY,D_EVALUE,D_CIGAR,J_SCORE,J_IDENTITY,J_EVALUE,J_CIGAR,FWR1_IMGT,FWR2_IMGT,FWR3_IMGT,FWR4_IMGT,CDR1_IMGT,CDR2_IMGT,CDR3_IMGT,CLONE,GERMLINE_IMGT_D_MASK,GERMLINE_V_CALL,GERMLINE_D_CALL,GERMLINE_J_CALL,MU_COUNT_SEQ_R,MU_COUNT_SEQ_S,MU_FREQ_SEQ_R,MU_FREQ_SEQ_S,ISOTYPE_by_splice,ISOTYPE
PASL_2_PA_11_plate_1_D11,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PASL_2_PA_11_plate_1_B8,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PASL_2_PA_11_plate_1_C2,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PASL_2_PA_11_plate_1_G10,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PASL_2_PA_11_plate_1_F1,0,Donor_11,PASL,Allergic_Individuals,Allergic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B107906_C14,8,SS2,B107906,PlasmaCells_2,PlasmaCells,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B107914_M3,8,SS2,B107914,PlasmaCells_1,PlasmaCells,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B107906_P14,8,SS2,B107906,PlasmaCells_2,PlasmaCells,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B107906_C22,8,SS2,B107906,PlasmaCells_2,PlasmaCells,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B107914_A20,8,SS2,B107914,PlasmaCells_1,PlasmaCells,bracer_B107914_A20_TRINITY_DN1_c11_g1_i1_H SS2_TS,GGTATCAACGCAGAGTACATGGGAGCTCTGAGAGAGGAGCCCAGCC...,True,True,False,NaN,False,IGH,"IGHV3-23*01,IGHV3-23D*01","IGHD2-21*01,IGHD2-21*02",IGHJ4*02,GAGGTGCAGCTGTTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGG...,GAGGTGCAGCTGTTGGAGTCTGGGGGA...GGCTTGGTACAGCCTG...,160.0,296.0,1.0,296.0,1.0,320.0,6.0,462.0,10.0,6.0,10.0,2.0,474.0,44.0,5.0,44.0,TGTGCGAAAGAGTTCGGATTGTGGTGGGTCTTTGACTACTGG,42.0,GAGGTGCAGCTGTTGGAGTCTGGGGGA...GGCTTGGTACAGCCTG...,463.0,1.0,5.260000e-132,159S296=,19.9,1.0,0.51,461S5N10=,85.3,1.0,1.960000e-20,473S4N44=,GAGGTGCAGCTGTTGGAGTCTGGGGGA...GGCTTGGTACAGCCTG...,ATGAGCTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTCT...,TACTACGCAGACTCCGTGAAG...GGCCGGTTCACCATCTCCAGAG...,TGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAG,GGATTCACCTTT............AGCAGCTATGCC,ATTAGTGGTAGT......GGTGGTAGCACA,GCGAAAGAGTTCGGATTGTGGTGGGTCTTTGACTAC,1047.0,GAGGTGCAGCTGTTGGAGTCTGGGGGA...GGCTTGGTACAGCCTG...,IGHV3-23*01,IGHD2-21*01,IGHJ4*02,0.0,0.0,0.0,0.0,IGHA1,IGHA1

In [58]:
adata.obs = df

In [60]:
import scanpy as sc

In [57]:
adata.obs.CLONE = adata.obs.CLONE.astype('category')

In [59]:
adata.write_h5ad('../data/Combined_PC_Changeo.h5ad')

... storing 'SEQUENCE_ID' as categorical
... storing 'SEQUENCE_INPUT' as categorical
... storing 'FUNCTIONAL' as categorical
... storing 'IN_FRAME' as categorical
... storing 'STOP' as categorical
... storing 'INDELS' as categorical
... storing 'LOCUS' as categorical
... storing 'V_CALL' as categorical
... storing 'D_CALL' as categorical
... storing 'J_CALL' as categorical
... storing 'SEQUENCE_VDJ' as categorical
... storing 'SEQUENCE_IMGT' as categorical
... storing 'JUNCTION' as categorical
... storing 'GERMLINE_IMGT' as categorical
... storing 'V_CIGAR' as categorical
... storing 'D_CIGAR' as categorical
... storing 'J_CIGAR' as categorical
... storing 'FWR1_IMGT' as categorical
... storing 'FWR2_IMGT' as categorical
... storing 'FWR3_IMGT' as categorical
... storing 'FWR4_IMGT' as categorical
... storing 'CDR1_IMGT' as categorical
... storing 'CDR2_IMGT' as categorical
... storing 'CDR3_IMGT' as categorical
... storing 'GERMLINE_IMGT_D_MASK' as categorical
... storing 'GERMLINE_V_CALL' as categorical
... storing 'GERMLINE_D_CALL' as categorical
... storing 'GERMLINE_J_CALL' as categorical
... storing 'ISOTYPE_by_splice' as categorical
... storing 'ISOTYPE' as categorical

In [60]:
adata.obs.CLONE

PASL_2_PA_11_plate_1_D11       NaN
PASL_2_PA_11_plate_1_B8        NaN
PASL_2_PA_11_plate_1_C2        NaN
PASL_2_PA_11_plate_1_G10       NaN
PASL_2_PA_11_plate_1_F1        NaN
                             ...
B107906_C14                    NaN
B107914_M3                     NaN
B107906_P14                    NaN
B107906_C22                    NaN
B107914_A20                 1047.0
Name: CLONE, Length: 5851, dtype: category
Categories (1170, float64): [111.0, 113.0, 116.0, 117.0, ..., 2253.0, 2254.0, 2255.0, 2264.0]